language: go
sudo: required

services:
  - docker

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

before_isntall:
  - docker pull jenkins
  - docker run -p 8080:8080 jenkins
  - docker ps -a

install:
  - go get github.com/stretchr/testify/assert